import Image from "next/image";
import React from "react";
import ErrorImg from "/public/images/backgrounds/maintenance.svg";
import MaintenanceAnimation from "./MaintenaneAnimations";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Maintenance",
  description: "Generated by create next app",
};
const Maintenance = () => {
  return (
    <>
      <div className="h-screen flex items-center  justify-center bg-white dark:bg-dark">
        <div className="text-center">
          <div className="max-w-3xl">
            <MaintenanceAnimation />
          </div>
          <h1 className="text-ld text-4xl mb-6">Maintenance Mode!!!</h1>
          <h6 className="text-xl text-ld">
            Website is Under Construction. Check back later!
          </h6>
          <Button asChild className="mt-6 mx-auto">
            <Link href="/">Go Back to Home</Link>
          </Button>
        </div>
      </div>
    </>
  );
};

export default Maintenance;
