import React from "react";
import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./css/globals.css";
import "@/utils/i18n";
import NextTopLoader from "nextjs-toploader";
import { Toaster } from "../components/ui/toaster";
import { CustomizerContextProvider } from "@/app/context/customizer-context";
import { ThemeProvider } from "@/components/ThemeProvider";

const dmSans = DM_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-dm-sans",
});

export const metadata: Metadata = {
  title: "TailwindAdmin - Nextjs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head>
          <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
        </head>
        <body className={dmSans.variable}>
          <NextTopLoader color="#5d87ff" showSpinner={false} />
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <CustomizerContextProvider>{children}</CustomizerContextProvider>
            <Toaster />
          </ThemeProvider>
        </body>
      </html>
    </>
  );
}
