import { Metadata } from "next";
import BreadcrumbComp from "../../../layout/shared/breadcrumb/BreadcrumbComp";
import ApexGradientChart from "@/app/components/charts/apex-charts/ApexGradientChart";
import CodePreview from "@/app/components/shared/CodePreview";

export const metadata: Metadata = {
  title: "Gradient Chart",
  description: "Generated by create next app",
};

const BCrumb = [
  {
    to: "/",
    title: "Home",
  },
  {
    title: "Chart Apex Gradient",
  },
];

const GradientChart = () => {
  return (
    <>
      <BreadcrumbComp title="Chart Apex Gradient" items={BCrumb} />
      <CodePreview
        component={<ApexGradientChart />}
        filePath="src/app/components/charts/ApexCharts/ApexGradientChart.tsx"
        title="Gradient Chart"
      />
    </>
  );
};

export default GradientChart;
