import React from "react";
import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./css/globals.css";
import "../utils/i18n";
import NextTopLoader from "nextjs-toploader";
import { Toaster } from "../components/ui/toaster";
import { CustomizerContextProvider } from "@/app/context/customizer-context";
import { AuthProvider } from "@/app/context/auth-context";
import SessionProviderComp from "./components/nextauth/SessionProvider";

import { getServerSession } from "next-auth/next";
import { authOptions } from "./api/auth/[...nextauth]/route";
import { ThemeProvider } from "@/components/ThemeProvider";

const dmSans = DM_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-dm-sans",
});

export const metadata: Metadata = {
  title: "TailwindAdmin - Nextjs",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Fetch session on the server
  const session = await getServerSession(authOptions);

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
      </head>
      <body className={`${dmSans.className}`}>
        <NextTopLoader color="#5d87ff" showSpinner={false} />
        <SessionProviderComp session={session}>
          <AuthProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <CustomizerContextProvider>{children}</CustomizerContextProvider>
            </ThemeProvider>
          </AuthProvider>
        </SessionProviderComp>
        <Toaster />
      </body>
    </html>
  );
}
