import { Metadata } from "next";
import BreadcrumbComp from "../../../layout/shared/breadcrumb/BreadcrumbComp";
import ApexAreaChart from "@/app/components/charts/apex-charts/ApexAreaChart";
import CodePreview from "@/app/components/shared/CodePreview";

export const metadata: Metadata = {
  title: "Area Chart",
  description: "Generated by create next app",
};

const BCrumb = [
  {
    to: "/",
    title: "Home",
  },
  {
    title: "Chart Apex Area",
  },
];

const AreaChart = () => {
  return (
    <>
      <BreadcrumbComp title="Chart Apex Area" items={BCrumb} />
      <CodePreview
        component={<ApexAreaChart />}
        filePath="src/app/components/charts/ApexCharts/ApexAreaChart.tsx"
        title="Area Chart"
      />
    </>
  );
};

export default AreaChart;
