import { Metadata } from "next";
import BreadcrumbComp from "../../../layout/shared/breadcrumb/BreadcrumbComp";
import ApexLineChart from "@/app/components/charts/apex-charts/ApexLineChart";
import CodePreview from "@/app/components/shared/CodePreview";

export const metadata: Metadata = {
  title: "Line Chart",
  description: "Generated by create next app",
};

const BCrumb = [
  {
    to: "/",
    title: "Home",
  },
  {
    title: "Chart Apex Line",
  },
];

const LineChart = () => {
  return (
    <>
      <BreadcrumbComp title="Chart Apex Line" items={BCrumb} />
      <CodePreview
        component={<ApexLineChart />}
        filePath="src/app/components/charts/ApexCharts/ApexLineChart.tsx"
        title="Line Chart"
      />
    </>
  );
};

export default LineChart;
