import { Metadata } from "next";
import BreadcrumbComp from "../../../layout/shared/breadcrumb/BreadcrumbComp";
import ApexCandleStick from "@/app/components/charts/apex-charts/ApexCandleSticks";
import CodePreview from "@/app/components/shared/CodePreview";

export const metadata: Metadata = {
  title: "Candlestick Chart",
  description: "Generated by create next app",
};

const BCrumb = [
  {
    to: "/",
    title: "Home",
  },
  {
    title: "Chart Apex Candlestick",
  },
];
const CandleStick = () => {
  return (
    <>
      <BreadcrumbComp title="Chart Apex Candlestick" items={BCrumb} />
      <CodePreview
        component={<ApexCandleStick />}
        filePath="src/app/components/charts/ApexCharts/ApexCandleSticks.tsx"
        title="Candlestick Chart"
      />
    </>
  );
};

export default CandleStick;
