import { Metadata } from "next";
import BreadcrumbComp from "../../../layout/shared/breadcrumb/BreadcrumbComp";
import ApexDoughnutChart from "@/app/components/charts/apex-charts/ApexDoughnutChart";
import ApexPieChart from "@/app/components/charts/apex-charts/ApexPieChart";
import CodePreview from "@/app/components/shared/CodePreview";

export const metadata: Metadata = {
  title: "Doughnut & Pie Chart",
  description: "Generated by create next app",
};

const BCrumb = [
  {
    to: "/",
    title: "Home",
  },
  {
    title: "Chart Apex Doughtnut & Pie",
  },
];

const DoughnutChart = () => {
  return (
    <>
      <BreadcrumbComp title="Chart Apex Doughtnut & Pie" items={BCrumb} />
      <div className="flex flex-col gap-6">
        {/* Doughnut Chart */}
        <div>
          <CodePreview
            component={<ApexDoughnutChart />}
            filePath="src/app/components/charts/ApexCharts/ApexDoughnutChart.tsx"
            title="Doughnut Chart"
          />
        </div>
        {/* Pie Chart */}
        <div>
          <CodePreview
            component={<ApexPieChart />}
            filePath="src/app/components/charts/ApexCharts/ApexPieChart.tsx"
            title="Pie Chart"
          />
        </div>
      </div>
    </>
  );
};

export default DoughnutChart;
