import React from 'react'
import BreadcrumbComp from '../../layout/shared/breadcrumb/BreadcrumbComp'
import type { Metadata } from 'next'
import ApiKeys from '@/app/components/theme-pages/api-keys/ApiKeys'


export const metadata: Metadata = {
    title: 'API Keys',
    description: 'Generated by create next app',
}


const BCrumb = [
    {
        to: '/',
        title: 'Dashboard',
    },
    {

        title: 'API Keys',
    },
]

function APIKey() {
    return (
        <>
            <BreadcrumbComp title='API Keys' items={BCrumb} />
            <ApiKeys />
        </>
    )
}

export default APIKey