import { NextRequest, NextResponse } from "next/server";
import { chatHistory } from "./chat-history/history";
import { Message } from "@/app/(DashboardLayout)/types/apps/ai-chat";

let ChatList: Message[] = [];

//  For resetting on browser refresh
const resetChats = [...ChatList];

// GET: Fetch chat messages
export async function GET(req: NextRequest) {
  const isBrowserRefreshed = req.headers.get("browserrefreshed");

  try {
    if (isBrowserRefreshed === "false") {
      // Return current chat list
      return NextResponse.json({
        status: 200,
        msg: "Fetched current chat list",
        data: ChatList,
      });
    } else {
      // Reset chat list
      ChatList = [...resetChats];
      return NextResponse.json({
        status: 200,
        msg: "Chat list reset on browser refresh",
        data: ChatList,
      });
    }
  } catch (error) {
    return NextResponse.json({
      status: 500,
      msg: "Server error",
    });
  }
}

// POST: Add new user message & generate AI response
export async function POST(req: NextRequest) {
  try {
    const userMsg = await req.json();

    const newId = ChatList.length + 1;

    // Add user message
    const userEntry: Message = {
      id: newId,
      sender: "user",
      text: userMsg.text,
    };
    ChatList.push(userEntry);
    const lowerText = userMsg.text.toLowerCase();

    const matchedQA = chatHistory.find(
      (item) => item.que.toLowerCase() === lowerText
    );

    let aiText = "";
    if (matchedQA) {
      aiText = matchedQA.preview;
    } else {
      if (lowerText.includes("title")) {
        aiText = `This is a mock response with a title.\n\n#  Example Title \n\nPlease note that this is not generated by an actual AI model.`;
      } else if (lowerText.includes("code")) {
        aiText = `\n\n\nfunction example() {\n  console.log('This is a mock code snippet.');\n}\n\n\n`;
        aiText = `Here is a code example:\n\n\`\`\`javascript\nfunction example() {\n  console.log('This is a mock code snippet.');\n}\n\`\`\` \n\nPlease note that this is not generated by an actual AI model.`;
      } else if (lowerText.includes("list")) {
        aiText = `This is a mock response with a list.\n\n1. First item\n2. Second item\n3. Third item\n\nPlease note that this is not generated by an actual AI model.`;
      } else if (lowerText.includes("alert")) {
        aiText = `⚠️ This is a mock warning. Proceed carefully. (This is not a real AI warning).`;
      } else {
        aiText = `This is a sample response for demonstration purposes only. It’s not generated by a real AI. Try including keywords like 'title','alert','code', or 'list'.`;
      }
    }

    //  AI reply
    const aiReply: Message = {
      id: newId + 1,
      sender: "ai",
      text: aiText,
    };
    ChatList.push(aiReply);

    return NextResponse.json({
      status: 200,
      msg: "Message added successfully",
      data: [userEntry, aiReply],
    });
  } catch (error) {
    return NextResponse.json({
      status: 400,
      msg: "Failed to add message",
    });
  }
}
