import React from 'react'
import type { Metadata } from 'next'
import BreadcrumbComp from '../../layout/shared/breadcrumb/BreadcrumbComp'
import Integartionpage from '@/app/components/theme-pages/integration/Integartionpage'


export const metadata: Metadata = {
    title: 'Integration',
    description: 'Generated by create next app',
}


const BCrumb = [
    {
        to: '/',
        title: 'Home',
    },
    {
       
        title: 'Integration',
    },
]


function Integration() {
    return (
        <>
            <BreadcrumbComp title='Integration' items={BCrumb} />
            <Integartionpage />
        </>
    )
}

export default Integration