import { Metadata } from "next";
import BreadcrumbComp from "../../../layout/shared/breadcrumb/BreadcrumbComp";
import ApexColumnChart from "@/app/components/charts/apex-charts/ApexColumnChart";
import CodePreview from "@/app/components/shared/CodePreview";

export const metadata: Metadata = {
  title: "Column Chart",
  description: "Generated by create next app",
};

const BCrumb = [
  {
    to: "/",
    title: "Home",
  },
  {
    title: "Chart Apex Column",
  },
];

const ColumnChart = () => {
  return (
    <>
      <BreadcrumbComp title="Chart Apex Column" items={BCrumb} />
      <CodePreview
        component={<ApexColumnChart />}
        filePath="src/app/components/charts/ApexCharts/ApexColumnChart.tsx"
        title="Column Chart"
      />
    </>
  );
};

export default ColumnChart;
