"use client";
import React, { useContext } from "react";
import { ImageContext } from "@/app/context/imageai-context";
import Image from "next/image";
import { Card } from "@/components/ui/card";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { HiInformationCircle } from "react-icons/hi";

function GeneratedImageDisplay() {
  const { displayedImages, isGenerating, isUsingMock } =
    useContext(ImageContext);

  return (
    <Card className="p-4">
      <div className="flex flex-col gap-4">
        <div>
          {isGenerating ? (
            <h3 className="text-xl font-bold">Generating...</h3>
          ) : (
            <h3 className="text-xl font-bold">Results</h3>
          )}
        </div>

        {/* Show alert only if using mock data */}
        {isUsingMock && (
          <Alert>
            <HiInformationCircle className="h-5 w-5 text-blue-500" />
            <AlertTitle>Mock Images</AlertTitle>
            <AlertDescription>
              These images are part of a simulated AI response for testing
              purposes. They were not generated by an actual AI system.
            </AlertDescription>
          </Alert>
        )}

        {isGenerating ? (
          <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-4">
            {[...Array(isUsingMock ? 4 : 1)].map((_, idx) => (
              <div
                key={idx}
                role="status"
                className="flex items-center justify-center h-56 max-w-sm bg-gray-300 rounded-lg animate-pulse dark:bg-gray-700"
              >
                <svg className="w-10 h-10 text-gray-200 dark:text-gray-600" />
              </div>
            ))}
          </div>
        ) : (
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
            {displayedImages.map((img: string, idx: number) => (
              <div key={idx} className="relative w-full aspect-square">
                <Image
                  src={img}
                  alt={`Generated ${idx}`}
                  fill
                  className="object-cover rounded-lg"
                />
              </div>
            ))}
          </div>
        )}
      </div>
    </Card>
  );
}

export default GeneratedImageDisplay;
